#!/bin/bash
x() {
    /home/cie/bin/notify "Az akkumulátor lemerül" "A jelenlegi töltöttség $E%." "$1"
    #echo "Az akkumulátor lemerül" "A jelenlegi töltöttség $E%."
}
y() {
    /home/cie/bin/notify "Az akkumulátor töltődik" "A jelenlegi töltöttség $E%." "$1"
    #echo "Az akkumulátor töltődik" "A jelenlegi töltöttség $E%."
    while charging; do sleep 60; done
    
}
charging() {
    acpi -b | grep Charging > /dev/null;
}

while true; do
    E=$(acpi -b | grep -oP '\d+%' | sed s/%//)
    if charging; then cmd=y; else cmd=x; fi
    if (( $E < 5 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery_empty.svg'; sleep 30
    elif (( $E < 10 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery_empty.svg'; sleep 60
    elif (( $E < 15 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery-caution.svg'; sleep 300
    elif (( $E < 50 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery-low.svg'; sleep 600
    elif (( $E < 66 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery_two_thirds.svg'; sleep 1200
    elif (( $E < 75 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery_third_fourth.svg'; sleep 1800
    elif (( $E < 100 )); then $cmd 'file:///usr/share/icons/Humanity/status/48/battery_full.svg'; sleep 2400
    fi
done

