#!/bin/bash
BAT="$(acpi -b | grep -oP '\d+%' | sed s/%//)"
if [ $BAT -lt 15 ]; then 
    if [ $BLINK = 1 ]; then BAT=""; fi
else
    BAT="$BAT%"
    acpi -b | grep Charging > /dev/null && BAT="$BAT+"
fi
echo -n $BAT
