#!/usr/bin/env python

import pygtk
pygtk.require('2.0')
import pynotify
import sys
import gtk
import os

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: notify <title> <text> [image uri]")
        sys.exit(1)

    if not pynotify.init("Notify"):
        sys.exit(1)


    # Image URI
    uri =sys.argv[3] if len(sys.argv) >= 4 else ""

    n = pynotify.Notification(sys.argv[1],sys.argv[2], uri)
    if not n.show():
        print("Failed to send notification")
        sys.exit(1)

